"""Bake the checked-in CC0 OBJ into bounded, allocation-free runtime geometry."""
import argparse
import hashlib
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'assets/models/44_magnum.obj'
TARGET = ROOT / 'src/runtime/reload_cartridge_mesh.hpp'
SOURCE_SHA256 = 'b78f01faf375f32a27e3f9356b7926dee8bfae8c03882d1b94fd94807fbd3b1d'

def generate():
    data = SOURCE.read_bytes()
    if hashlib.sha256(data).hexdigest() != SOURCE_SHA256:
        raise ValueError('Unknown cartridge OBJ identity')
    vertices, faces = [], []
    for line in data.decode('utf-8').splitlines():
        parts = line.split()
        if not parts:
            continue
        if parts[0] == 'v':
            x, y, z = map(float, parts[1:])
            if not all(math.isfinite(v) for v in (x, y, z)):
                raise ValueError('Non-finite vertex')
            # Right-handed rotation: OBJ +Y cartridge axis becomes grip -Z.
            vertices.append((x, z, -.0475 + .030494 - y))
        elif parts[0] == 'f':
            if len(parts) != 4:
                raise ValueError('Expected triangles')
            faces.append(tuple(int(p.split('/')[0]) - 1 for p in parts[1:]))
    if len(vertices) != 122 or len(faces) != 224 or any(
            i < 0 or i >= len(vertices) for face in faces for i in face):
        raise ValueError('Unexpected mesh topology')
    def f(value):
        return f'{value:.9f}F'
    lines = ['#pragma once', '#include "runtime/vr_types.hpp"', '#include <array>',
             '// Generated by tools/import_reload_cartridge.py; CC0 Pichuliru.',
             '// Source identity and attribution: assets/models/README.md.',
             'namespace cojvr::runtime::reload_mesh {',
             'inline constexpr std::array<Vec3,122> vertices{{']
    lines += ['    {' + ','.join(map(f, v)) + '},' for v in vertices]
    lines += ['}};', 'inline constexpr std::array<std::array<unsigned,3>,224> triangles{{']
    lines += ['    {' + ','.join(map(str, face)) + '},' for face in faces]
    lines += ['}};', '}']
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = generate()
    if args.check:
        if TARGET.read_text(encoding='utf-8') != output:
            raise SystemExit('Baked cartridge differs from source OBJ')
    else:
        TARGET.write_text(output, encoding='utf-8')
    print('CC0 cartridge: 122 vertices, 224 triangles; source and bake verified')
